### PR TITLE
171 add masthead to footer

### LINKED ISSUE #171: Masthead isn't accessible from the main site
It's hard to get to https://stanforddaily.com/masthead/ unless you actually type in the URL. There should be a link in the header / footer to get to the "Masthead".

### PR DESCRIPTION
**Pull request by sbcatania**
## Reasons for making this change

Remove extra grind things, move magazine, and add masthead to footer

## Related tickets

Fixes #171

## Screenshots

Screen Shot 2021-07-07 at 1 53 29 AM

### CODE REVIEW

**Comment by sbcatania** [comment]
@hs4man21 this also changed all these files in path `pages/category/[slug1]/[slug2]/[slug3]/[slug4]/[slug5]/index 2.tsx ` and similar, I think this is incorrect? Let me know, my VS code has been doing this all day and I don't know why -- please remove these files if they're irrelevant.

**Comment by hs4man21** [comment]
> @hs4man21 this also changed all these files in path `pages/category/[slug1]/[slug2]/[slug3]/[slug4]/[slug5]/index 2.tsx ` and similar, I think this is incorrect? Let me know, my VS code has been doing this all day and I don't know why -- please remove these files if they're irrelevant.

Yeah, we don't want to merge those. We can add the paths to .gitignore or something if it's an issue, but for this PR I'm also happy to fix.

**Comment by sbcatania** [comment]
> > @hs4man21 this also changed all these files in path `pages/category/[slug1]/[slug2]/[slug3]/[slug4]/[slug5]/index 2.tsx ` and similar, I think this is incorrect? Let me know, my VS code has been doing this all day and I don't know why -- please remove these files if they're irrelevant.
> 
> Yeah, we don't want to merge those. We can add the paths to .gitignore or something if it's an issue, but for this PR I'm also happy to fix.

Ok, yeah @hs4man21 if you could do that, that would be great! Feel free to merge once done!

**Review by hs4man21 — APPROVED** [review]
Resolved issue with extra files - changes lgtm!

**Pull request merged**
